'use client';
import { FormEvent, useEffect, useState } from 'react';
import { AdminNav } from '../components/admin-nav';
import { api } from '../lib/api';
type Item={id:string;product_name:string;sku:string;quantity:number};
type ReturnRow={id:string;status:string;reason:string;requested_at:string;order_number:string;refundable_amount:string;currency:string;item_count:string;items:Item[];refund_amount:string|null;refund_currency:string|null;refund_account_name:string|null};
type Warehouse={id:string;name:string;code:string;is_active:boolean}; type Account={id:string;name:string;currency:string;is_active:boolean};
const labels:Record<string,string>={REQUESTED:'Talep alındı',APPROVED:'Onaylandı',RECEIVED:'Depoya ulaştı',INSPECTED:'İncelendi',REFUNDED:'İade ödendi',REJECTED:'Reddedildi',CANCELLED:'İptal'};
const money=(v:string,c:string)=>Number(v).toLocaleString('tr-TR',{style:'currency',currency:c});
export default function Returns(){
 const [rows,setRows]=useState<ReturnRow[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[message,setMessage]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[dispositions,setDispositions]=useState<Record<string,string>>({}),[warehouseIds,setWarehouseIds]=useState<Record<string,string>>({}),[refunds,setRefunds]=useState<Record<string,string>>({}),[accountIds,setAccountIds]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null);
 const load=()=>Promise.all([api<ReturnRow[]>('/returns/admin'),api<Warehouse[]>('/admin/warehouse/locations'),api<Account[]>('/admin/finance/accounts')]).then(([returns,locations,finance])=>{setRows(returns);setWarehouses(locations.filter(x=>x.is_active));setAccounts(finance.filter(x=>x.is_active));}).catch(e=>setMessage(e.message));
 useEffect(()=>{void load()},[]);
 const note=(id:string)=>notes[id]??''; const setNote=(id:string,value:string)=>setNotes(current=>({...current,[id]:value}));
 async function act(id:string,action:string,body:unknown={}){setBusy(`${id}:${action}`);setMessage('');try{await api(`/returns/${id}/${action}`,{method:'POST',body:JSON.stringify(body)});setMessage('İade işlemi kaydedildi.');await load();}catch(error){setMessage(error instanceof Error?error.message:'İşlem yapılamadı')}finally{setBusy(null)}}
 const submit=(event:FormEvent,id:string,action:string,body:unknown)=>{event.preventDefault();void act(id,action,body)};
 return <main><AdminNav/><section><p>SİPARİŞ / İADE VE DEĞİŞİM</p><h1>İade operasyonları</h1><p>Akış: talep → onay → depoya kabul → inceleme/stok ayrımı → finans iadesi. Her işlem kayıt altına alınır.</p>{message&&<p role="status">{message}</p>}<div className="cards">{rows.length?rows.map(row=>{
  const warehouseId=warehouseIds[row.id]??warehouses[0]?.id??''; const disposition=dispositions[row.id]??'SELLABLE'; const financeAccounts=accounts.filter(account=>account.currency===row.currency); const accountId=accountIds[row.id]??financeAccounts[0]?.id??''; const refund=refunds[row.id]??row.refundable_amount;
  return <article key={row.id}><p>{labels[row.status]??row.status} · {new Date(row.requested_at).toLocaleString('tr-TR')}</p><h2>{row.order_number}</h2><p>{row.items.map(item=>`${item.product_name} × ${item.quantity}`).join(', ')||`${row.item_count} ürün`}</p><p>Neden: {row.reason}</p>
   {row.status==='REQUESTED'&&<form onSubmit={event=>submit(event,row.id,'approve',{notes:note(row.id)||undefined})}><label>Onay notu<input value={note(row.id)} onChange={event=>setNote(row.id,event.target.value)}/></label><div className="button-row"><button disabled={busy!==null}>İadeyi onayla</button><button type="button" className="secondary" disabled={busy!==null} onClick={()=>void act(row.id,'reject',{notes:note(row.id)||undefined})}>Reddet</button></div></form>}
   {row.status==='APPROVED'&&<button disabled={busy!==null} onClick={()=>void act(row.id,'receive',{notes:note(row.id)||undefined})}>Depoya teslim al</button>}
   {row.status==='RECEIVED'&&<form onSubmit={event=>submit(event,row.id,'inspection',{warehouseId,disposition,notes:note(row.id)||undefined})}><label>İade deposu<select required value={warehouseId} onChange={event=>setWarehouseIds(current=>({...current,[row.id]:event.target.value}))}><option value="">Depo seçin</option>{warehouses.map(item=><option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select></label><label>Stok durumu<select value={disposition} onChange={event=>setDispositions(current=>({...current,[row.id]:event.target.value}))}><option value="SELLABLE">Satılabilir stoğa al</option><option value="QUARANTINE">Karantinaya al</option><option value="DAMAGED">Hasarlı olarak ayır</option></select></label><label>İnceleme notu<input value={note(row.id)} onChange={event=>setNote(row.id,event.target.value)}/></label><button disabled={busy!==null}>İncelemeyi tamamla</button></form>}
   {row.status==='INSPECTED'&&<form onSubmit={event=>submit(event,row.id,'refund',{accountId,amount:Number(refund),referenceNumber:note(row.id)||undefined})}><p>İade üst sınırı: {money(row.refundable_amount,row.currency)}</p><label>Çıkış hesabı<select required value={accountId} onChange={event=>setAccountIds(current=>({...current,[row.id]:event.target.value}))}><option value="">Hesap seçin</option>{financeAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>İade tutarı<input required min="0.01" step="0.01" type="number" value={refund} onChange={event=>setRefunds(current=>({...current,[row.id]:event.target.value}))}/></label><label>Referans / not<input value={note(row.id)} onChange={event=>setNote(row.id,event.target.value)}/></label><button disabled={busy!==null}>Finans iadesini kaydet</button></form>}
   {row.status==='REFUNDED'&&<p><strong>{row.refund_account_name??'Finans hesabı'} üzerinden {money(row.refund_amount??'0',row.refund_currency??row.currency)} iade edildi.</strong></p>}
  </article>}) : <article><p>Henüz iade talebi yok.</p></article>}</div></section></main>;
}
