ALTER TYPE dealer_status ADD VALUE IF NOT EXISTS 'RECEIVED';
ALTER TYPE dealer_status ADD VALUE IF NOT EXISTS 'REVIEWING';
ALTER TYPE dealer_status ADD VALUE IF NOT EXISTS 'DOCUMENTS_REQUESTED';
ALTER TYPE dealer_status ADD VALUE IF NOT EXISTS 'REJECTED';
