'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { AdminNav } from '../components/admin-nav';
import { api } from '../lib/api';
import styles from './products.module.css';

type Product={id:string;sku:string;barcode:string|null;slug:string;name:string;description:string|null;status:string};
type Level={id:string;name:string}; type Price={id:string;product_id:string;amount:string;scope:string;dealer_level_name:string|null}; type Cost={id:string;product_id:string;unit_cost:string;supplier_name:string|null};
const money=(value:string)=>Number(value).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
export default function Products(){
  const [deleting,setDeleting]=useState(false);
  async function removeSelected(){
    const ids=selected.filter(id=>products.some(product=>product.id===id));
    if(!ids.length||!window.confirm(`${ids.length} ürün kalıcı silinsin mi? Fiyatları ve maliyetleri de kaldırılır. Sipariş geçmişine bağlı ürünler silinmez.`)) return;
    setDeleting(true);let deleted=0;const errors:string[]=[];
    try{for(const id of ids){try{await api(`/admin/products/${id}`,{method:'DELETE'});deleted++;}catch(e){errors.push(`${products.find(p=>p.id===id)?.name}: ${e instanceof Error?e.message:'Silinemedi'}`);}}setSelected([]);await load();setMessage(`${deleted} ürün silindi. ${errors.join(' ')}`);}finally{setDeleting(false);}
  }
  const [products,setProducts]=useState<Product[]>([]),[levels,setLevels]=useState<Level[]>([]),[prices,setPrices]=useState<Price[]>([]),[costs,setCosts]=useState<Cost[]>([]); const [message,setMessage]=useState(''); const [query,setQuery]=useState('');const [status,setStatus]=useState('ALL');const [selected,setSelected]=useState<string[]>([]); const [newOpen,setNewOpen]=useState(false); const [priceOpen,setPriceOpen]=useState(false);
  const [form,setForm]=useState({name:'',sku:'',slug:'',barcode:'',description:'',status:'DRAFT'});const [price,setPrice]=useState({productId:'',scope:'GLOBAL',amount:'',dealerLevelId:''});const [cost,setCost]=useState({productId:'',unitCost:'',supplierName:'',note:''});
  const load=()=>Promise.all([api<Product[]>('/admin/products'),api<Level[]>('/admin/dealers/levels'),api<Price[]>('/admin/prices'),api<Cost[]>('/admin/product-costs')]).then(([a,b,c,d])=>{setProducts(a);setLevels(b);setPrices(c);setCosts(d)}).catch(e=>setMessage(e instanceof Error?e.message:'Ürünler yüklenemedi'));
  useEffect(()=>{void load();},[]);
  const shown=useMemo(()=>products.filter(product=>(status==='ALL'||product.status===status)&&[product.name,product.sku,product.barcode,product.slug].filter(Boolean).join(' ').toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))),[products,status,query]);
  const globalPrice=(id:string)=>prices.find(item=>item.product_id===id&&item.scope==='GLOBAL'); const latestCost=(id:string)=>costs.find(item=>item.product_id===id);
  const toggle=(id:string)=>setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);
  async function submit(event:FormEvent){event.preventDefault();try{await api('/admin/products',{method:'POST',body:JSON.stringify({...form,barcode:form.barcode||undefined,description:form.description||undefined})});setForm({name:'',sku:'',slug:'',barcode:'',description:'',status:'DRAFT'});setNewOpen(false);setMessage('Ürün kaydedildi.');void load();}catch(error){setMessage(error instanceof Error?error.message:'Ürün kaydedilemedi');}}
  async function savePrice(event:FormEvent){event.preventDefault();try{await api('/admin/prices',{method:'POST',body:JSON.stringify({productId:price.productId,scope:price.scope,amount:Number(price.amount),currency:'TRY',dealerLevelId:price.scope==='DEALER_LEVEL'?price.dealerLevelId:undefined})});setPrice(data=>({...data,amount:''}));setMessage('TL fiyatı kaydedildi.');void load();}catch(error){setMessage(error instanceof Error?error.message:'Fiyat kaydedilemedi');}}
  async function saveCost(event:FormEvent){event.preventDefault();try{await api('/admin/product-costs',{method:'POST',body:JSON.stringify({...cost,unitCost:Number(cost.unitCost),supplierName:cost.supplierName||undefined,note:cost.note||undefined})});setCost({productId:'',unitCost:'',supplierName:'',note:''});setMessage('Ürün maliyeti kaydedildi.');void load();}catch(error){setMessage(error instanceof Error?error.message:'Maliyet kaydedilemedi');}}
  return <main><AdminNav/><section className={styles.page}><div className={styles.titleRow}><div><p>ÜRÜN YÖNETİMİ</p><h1>Ürünler</h1></div><div className={styles.catalogLinks}><Link href="/stok">Stok yönetimi</Link><Link href="/medya">Medya merkezi</Link></div></div>{message&&<p className={styles.notice} role="status">{message}</p>}
  <div className={styles.toolbar}><label className={styles.search}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün adı, SKU, barkod veya site adresi ara"/></label><label className={styles.statusSelect}>Durum<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Tümü</option><option value="ACTIVE">Yayında</option><option value="DRAFT">Taslak</option></select></label><button type="button" className={styles.secondaryAction} onClick={()=>setPriceOpen(open=>!open)}>₺ Fiyat / maliyet</button><button type="button" onClick={()=>setNewOpen(open=>!open)}>＋ Yeni ürün</button></div>
  {selected.length>0&&<div className={styles.selection}><b>{selected.length} ürün seçildi</b><button type="button" disabled={deleting} onClick={()=>void removeSelected()}>{deleting?'Siliniyor…':'Seçili ürünleri sil'}</button><button type="button" disabled={deleting} onClick={()=>setSelected([])}>Seçimi kaldır</button></div>}
  {newOpen&&<form className={styles.editor} onSubmit={submit}><header><h2>Yeni ürün</h2><button type="button" className={styles.close} onClick={()=>setNewOpen(false)}>×</button></header><div className={styles.tabHint}><b>Genel bilgiler</b><span>Fiyat, maliyet, stok ve görsel adımları ürün kaydından sonra eklenir.</span></div><div className={styles.formGrid}><label>Ürün adı<input required value={form.name} onChange={e=>setForm(data=>({...data,name:e.target.value}))}/></label><label>SKU<input required value={form.sku} onChange={e=>setForm(data=>({...data,sku:e.target.value}))}/></label><label>Site adresi (slug)<input required value={form.slug} onChange={e=>setForm(data=>({...data,slug:e.target.value}))}/></label><label>Barkod<input value={form.barcode} onChange={e=>setForm(data=>({...data,barcode:e.target.value}))}/></label><label>Yayın durumu<select value={form.status} onChange={e=>setForm(data=>({...data,status:e.target.value}))}><option value="DRAFT">Taslak</option><option value="ACTIVE">Yayında</option></select></label><label className={styles.wide}>Açıklama<textarea value={form.description} onChange={e=>setForm(data=>({...data,description:e.target.value}))}/></label></div><footer><button>Ürünü kaydet</button></footer></form>}
  {priceOpen&&<div className={styles.priceGrid}><form className={styles.editor} onSubmit={savePrice}><header><h2>Satış fiyatı</h2></header><label>Ürün<select required value={price.productId} onChange={e=>setPrice(data=>({...data,productId:e.target.value}))}><option value="">Ürün seç</option>{products.map(product=><option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Fiyat türü<select value={price.scope} onChange={e=>setPrice(data=>({...data,scope:e.target.value,dealerLevelId:''}))}><option value="GLOBAL">Site satış fiyatı</option><option value="DEALER_LEVEL">Bayi seviye fiyatı</option></select></label>{price.scope==='DEALER_LEVEL'&&<label>Bayi seviyesi<select required value={price.dealerLevelId} onChange={e=>setPrice(data=>({...data,dealerLevelId:e.target.value}))}><option value="">Seviye seç</option>{levels.map(level=><option value={level.id} key={level.id}>{level.name}</option>)}</select></label>}<label>Tutar (TL)<input required min="0" step="0.01" type="number" value={price.amount} onChange={e=>setPrice(data=>({...data,amount:e.target.value}))}/></label><footer><button>Fiyatı kaydet</button></footer></form><form className={styles.editor} onSubmit={saveCost}><header><h2>Ürün maliyeti</h2></header><label>Ürün<select required value={cost.productId} onChange={e=>setCost(data=>({...data,productId:e.target.value}))}><option value="">Ürün seç</option>{products.map(product=><option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Birim maliyet (TL)<input required min="0" step="0.01" type="number" value={cost.unitCost} onChange={e=>setCost(data=>({...data,unitCost:e.target.value}))}/></label><label>Tedarikçi<input value={cost.supplierName} onChange={e=>setCost(data=>({...data,supplierName:e.target.value}))}/></label><label>Not<input value={cost.note} onChange={e=>setCost(data=>({...data,note:e.target.value}))}/></label><footer><button>Maliyeti kaydet</button></footer></form></div>}
  <div className={styles.tableWrap}><table><thead><tr><th><input type="checkbox" aria-label="Tüm ürünleri seç" checked={shown.length>0&&selected.length===shown.length} onChange={e=>setSelected(e.target.checked?shown.map(product=>product.id):[])}/></th><th>No</th><th>Ürün bilgileri</th><th>Site fiyatı</th><th>Maliyet</th><th>Stok</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody>{shown.map((product,index)=>{const sale=globalPrice(product.id),costItem=latestCost(product.id);return <tr key={product.id}><td><input type="checkbox" aria-label={`${product.name} seç`} checked={selected.includes(product.id)} onChange={()=>toggle(product.id)}/></td><td>{index+1}</td><td><b>{product.name}</b><small>Kodu: {product.sku}</small><small>Barkod: {product.barcode??'—'} · /{product.slug}</small></td><td><b>{sale?money(sale.amount):'Fiyat girilmedi'}</b><small>{sale?'Site satış fiyatı':'Fiyat menüsünden ekleyin'}</small></td><td><b>{costItem?money(costItem.unit_cost):'Maliyet girilmedi'}</b><small>{costItem?.supplier_name??'—'}</small></td><td><Link className={styles.stockLink} href="/stok">Stok işlemi →</Link></td><td><span className={product.status==='ACTIVE'?styles.active:styles.draft}>{product.status==='ACTIVE'?'● Yayında':'● Taslak'}</span></td><td><div className={styles.actions}><Link href={`/medya?product=${product.id}`} title="Görsel yönetimi">▧</Link><button type="button" onClick={()=>{setPrice(data=>({...data,productId:product.id}));setPriceOpen(true)}} title="Fiyat/maliyet">₺</button><a href={`https://www.trextea.com.tr/urunler/${product.slug}`} target="_blank" rel="noreferrer" title="Ürünü görüntüle">↗</a></div></td></tr>})}</tbody></table>{shown.length===0&&<div className={styles.empty}>Bu arama ve filtrede ürün bulunamadı.</div>}</div><p className={styles.count}>{shown.length} ürün listeleniyor.</p></section></main>;
}
