import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
@Injectable()
export class WarehouseService {
  constructor(private readonly db: DatabaseService) {}
  async dashboard() {
    const result = await this.db.query<{ waiting: string; picking: string; packing: string; critical_stock: string; returns_pending: string }>(`SELECT (SELECT count(*)::text FROM orders WHERE status IN ('PAID','PROCESSING')) waiting, (SELECT count(*)::text FROM picking_sessions WHERE status IN ('OPEN','IN_PROGRESS')) picking, (SELECT count(*)::text FROM picking_sessions ps LEFT JOIN packing_sessions pk ON pk.picking_session_id=ps.id WHERE ps.status='COMPLETED' AND pk.id IS NULL) packing, (SELECT count(*)::text FROM inventory WHERE physical_quantity-reserved_quantity <= 5) critical_stock, (SELECT count(*)::text FROM returns WHERE status NOT IN ('REFUNDED','REJECTED','CANCELLED')) returns_pending`);
    return result.rows[0];
  }
  async listPicks() { return (await this.db.query(`SELECT ps.id, ps.status, ps.created_at, o.order_number, w.name AS warehouse_name, u.email AS assigned_email, COALESCE(SUM(pi.expected_quantity),0) AS expected_items, COALESCE(SUM(pi.picked_quantity),0) AS picked_items FROM picking_sessions ps JOIN orders o ON o.id=ps.order_id JOIN warehouses w ON w.id=ps.warehouse_id LEFT JOIN users u ON u.id=ps.assigned_to LEFT JOIN picking_items pi ON pi.picking_session_id=ps.id GROUP BY ps.id,o.order_number,w.name,u.email ORDER BY ps.created_at DESC LIMIT 50`)).rows; }
  async criticalStock() { return (await this.db.query(`SELECT p.id, p.name, w.name AS warehouse_name, i.physical_quantity, i.reserved_quantity, i.physical_quantity-i.reserved_quantity AS available_quantity FROM inventory i JOIN products p ON p.id=i.product_id JOIN warehouses w ON w.id=i.warehouse_id WHERE i.physical_quantity-i.reserved_quantity <= 5 ORDER BY available_quantity ASC, p.name LIMIT 100`)).rows; }
  async createPick(orderId:string,warehouseId:string,userId:string) { const order=await this.db.query("SELECT id FROM orders WHERE id=$1 AND status='PAID'",[orderId]); if(!order.rowCount) throw new NotFoundException('Paid order not found'); const pick=await this.db.query<{id:string}>('INSERT INTO picking_sessions (order_id,warehouse_id,assigned_to,status) VALUES ($1,$2,$3,$4) RETURNING id',[orderId,warehouseId,userId,'IN_PROGRESS']); const items=await this.db.query<{id:string;quantity:number}>('SELECT id,quantity FROM order_items WHERE order_id=$1',[orderId]); for(const item of items.rows) await this.db.query('INSERT INTO picking_items (picking_session_id,order_item_id,expected_quantity) VALUES ($1,$2,$3)',[pick.rows[0].id,item.id,item.quantity]); return pick.rows[0]; }
  async completePick(id:string,userId:string) { return this.db.transaction(async client=>{ const pick=await client.query<{id:string}>('SELECT id FROM picking_sessions WHERE id=$1 AND status IN (\'OPEN\',\'IN_PROGRESS\') FOR UPDATE',[id]); if(!pick.rowCount) throw new NotFoundException('Aktif toplama listesi bulunamadı'); const missing=await client.query('SELECT 1 FROM picking_items WHERE picking_session_id=$1 AND picked_quantity<expected_quantity LIMIT 1',[id]); if(missing.rowCount) throw new Error('Tüm ürünler toplanmadan liste tamamlanamaz'); await client.query('UPDATE picking_sessions SET status=\'COMPLETED\',completed_at=now() WHERE id=$1',[id]); await client.query('INSERT INTO packing_sessions(picking_session_id,packed_by) VALUES ($1,$2)',[id,userId]); return {id,status:'COMPLETED'}; }); }
  async completePacking(pickId:string,userId:string) { return this.db.transaction(async client=>{ const packing=await client.query<{id:string;order_id:string}>(`SELECT pk.id,ps.order_id FROM packing_sessions pk JOIN picking_sessions ps ON ps.id=pk.picking_session_id WHERE pk.picking_session_id=$1 AND pk.packed_at IS NULL FOR UPDATE`,[pickId]); if(!packing.rowCount) throw new NotFoundException('Açık paketleme kaydı bulunamadı'); await client.query('UPDATE packing_sessions SET packed_by=$1,packed_at=now(),verification_code=$2 WHERE id=$3',[userId,`TRX-${Date.now()}`,packing.rows[0].id]); await client.query(`UPDATE orders SET status='PROCESSING' WHERE id=$1 AND status='PAID'`,[packing.rows[0].order_id]); return {pickId,status:'READY_FOR_SHIPMENT'}; }); }
}
