'use client';
import { FormEvent, useEffect, useState } from 'react';
import { AdminNav } from '../components/admin-nav';
import { api } from '../lib/api';

type Rule={id:string;product_id:string;recipient_user_id:string;recipient_kind:string;amount_per_unit:string;currency:string;is_active:boolean;product_name:string;sku:string;recipient_email:string};
type Entry={id:string;amount:string;currency:string;status:string;entry_kind:string;created_at:string;finalized_at:string|null;paid_at:string|null;reversed_at:string|null;note:string|null;order_number:string;product_name:string;quantity:number;recipient_email:string;recipient_kind:string};
type Option={id:string;name?:string;sku?:string;email?:string;role?:string;currency?:string;account_type?:string};
type Data={rules:Rule[];entries:Entry[];staff:Option[];products:Option[];accounts:Option[]};
const money=(value:string,currency:string)=>Number(value).toLocaleString('tr-TR',{style:'currency',currency});
const labels:Record<string,string>={PENDING:'Bekliyor',CONFIRMED:'Kesinleşti',PAID:'Ödendi',REVERSED:'Ters kayıt',STAFF:'Personel',MANAGER:'Yönetici',EARN:'Prim',REVERSAL:'Ters kayıt'};
export default function CommissionPage(){
 const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
 const [form,setForm]=useState({productId:'',recipientUserId:'',recipientKind:'STAFF',amountPerUnit:''});
 const [accounts,setAccounts]=useState<Record<string,string>>({});
 const load=()=>api<Data>('/admin/commissions').then(setData).catch(e=>setMessage(e.message));
 useEffect(()=>{void load()},[]);
 async function create(event:FormEvent){event.preventDefault();setBusy('rule');try{await api('/admin/commissions/staff-rules',{method:'POST',body:JSON.stringify({...form,amountPerUnit:Number(form.amountPerUnit)})});setMessage('Prim kuralı kaydedildi. Bu kural, sonraki teslim edilen siparişlerde uygulanır.');setForm(x=>({...x,amountPerUnit:''}));await load()}catch(e){setMessage(e instanceof Error?e.message:'Kural kaydedilemedi')}finally{setBusy('')}}
 async function act(path:string,ok:string,body?:unknown){setBusy(path);try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});setMessage(ok);await load()}catch(e){setMessage(e instanceof Error?e.message:'İşlem tamamlanamadı')}finally{setBusy('')}}
 async function remove(id:string){if(!confirm('Bu prim kuralını kapatmak istiyor musunuz? Önceki prim kayıtları korunur.'))return;setBusy(id);try{await api(`/admin/commissions/rules/${id}`,{method:'DELETE'});setMessage('Prim kuralı kapatıldı.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Kural kapatılamadı')}finally{setBusy('')}}
 return <main><AdminNav/><section><p>FİNANS / PRİM MOTORU</p><h1>Personel ve yönetici primleri</h1><p>Ürün başına sabit TL/adet kuralı tanımlanır. Teslim edilen sipariş prim oluşturur; finans sorumlusu kesinleştirip seçilen kasadan ödeme yapar. İade veya iptal kaydı silmez, ters hareket oluşturur.</p>{message&&<p role="status">{message}</p>}
 <form className="form-card" onSubmit={create}><h2>Yeni ürün primi</h2><div className="form-grid"><label>Ürün<select required value={form.productId} onChange={e=>setForm(x=>({...x,productId:e.target.value}))}><option value="">Seçin</option>{data?.products.map(p=><option key={p.id} value={p.id}>{p.name} {p.sku?`(${p.sku})`:''}</option>)}</select></label><label>Prim alıcısı<select required value={form.recipientUserId} onChange={e=>setForm(x=>({...x,recipientUserId:e.target.value}))}><option value="">Seçin</option>{data?.staff.map(s=><option key={s.id} value={s.id}>{s.email} · {s.role}</option>)}</select></label><label>Prim tipi<select value={form.recipientKind} onChange={e=>setForm(x=>({...x,recipientKind:e.target.value}))}><option value="STAFF">Personel</option><option value="MANAGER">Yönetici</option></select></label><label>Adet başına prim (TL)<input required type="number" min="0" step="0.01" value={form.amountPerUnit} onChange={e=>setForm(x=>({...x,amountPerUnit:e.target.value}))}/></label></div><button disabled={busy==='rule'}>{busy==='rule'?'Kaydediliyor…':'Kuralı kaydet'}</button></form>
 <h2>Aktif prim kuralları</h2><div style={{overflowX:'auto'}}><table><thead><tr><th>Ürün</th><th>Alıcı</th><th>Tip</th><th>Adet primi</th><th></th></tr></thead><tbody>{data?.rules.filter(r=>r.is_active).map(r=><tr key={r.id}><td>{r.product_name}<br/><small>{r.sku}</small></td><td>{r.recipient_email}</td><td>{labels[r.recipient_kind]??r.recipient_kind}</td><td>{money(r.amount_per_unit,r.currency)}</td><td><button className="secondary" disabled={busy===r.id} onClick={()=>void remove(r.id)}>Kuralı kapat</button></td></tr>)}</tbody></table></div>{data&&!data.rules.some(r=>r.is_active)&&<p>Henüz aktif prim kuralı yok.</p>}
 <h2>Prim hareketleri</h2><div style={{overflowX:'auto'}}><table><thead><tr><th>Sipariş / ürün</th><th>Alıcı</th><th>Tutar</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{data?.entries.map(e=>{const account=accounts[e.id]||'';return <tr key={e.id}><td><strong>{e.order_number}</strong><br/>{e.product_name} · {e.quantity} adet</td><td>{e.recipient_email}<br/><small>{labels[e.recipient_kind]??e.recipient_kind}</small></td><td>{money(e.amount,e.currency)}</td><td>{labels[e.status]??e.status}<br/><small>{new Date(e.created_at).toLocaleString('tr-TR')}</small></td><td>{e.entry_kind==='EARN'&&e.status==='PENDING'&&<button disabled={busy===`/admin/commissions/entries/${e.id}/finalize`} onClick={()=>void act(`/admin/commissions/entries/${e.id}/finalize`,'Prim kesinleştirildi.')}>Kesinleştir</button>}{e.entry_kind==='EARN'&&e.status==='CONFIRMED'&&<span className="button-row"><select aria-label="Ödeme hesabı" value={account} onChange={x=>setAccounts(a=>({...a,[e.id]:x.target.value}))}><option value="">Kasa seçin</option>{data?.accounts.filter(a=>a.currency===e.currency).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button disabled={!account||busy===`/admin/commissions/entries/${e.id}/pay`} onClick={()=>void act(`/admin/commissions/entries/${e.id}/pay`,'Prim ödemesi finansa işlendi.',{accountId:account})}>Öde</button></span>}{e.entry_kind==='EARN'&&['PENDING','CONFIRMED'].includes(e.status)&&<button className="secondary" disabled={busy===`/admin/commissions/entries/${e.id}/reverse`} onClick={()=>void act(`/admin/commissions/entries/${e.id}/reverse`,'Ters prim kaydı oluşturuldu.',{note:'Yönetici ters kaydı'})}>Ters kayıt</button>}{e.entry_kind==='REVERSAL'&&<small>{e.note}</small>}</td></tr>})}</tbody></table></div>{data&&!data.entries.length&&<p>Teslim edilmiş ve primi olan siparişlerde hareketler burada görünür.</p>}</section></main>;
}
