import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { RequestUser } from '../auth/auth.types';
import { DatabaseService } from '../database/database.service';
import { CreateCommissionRuleDto } from './dto/create-commission-rule.dto';
import { CreateCommissionRuleV5Dto, PayCommissionDto, ReverseCommissionDto } from './dto/commission-operation.dto';
@Injectable()
export class CommissionsService {
  constructor(private readonly db: DatabaseService) {}
  async createRule(dto: CreateCommissionRuleDto) { return (await this.db.query<{ id: string }>('INSERT INTO commission_rules (dealer_level_id,product_id,amount_per_unit) VALUES ($1,$2,$3) RETURNING id', [dto.dealerLevelId ?? null, dto.productId ?? null, dto.amountPerUnit])).rows[0]; }
  async createStaffRule(dto: CreateCommissionRuleV5Dto, actor: RequestUser) {
    if (!['STAFF','MANAGER'].includes(dto.recipientKind)) throw new BadRequestException('Prim tipi personel veya yönetici olmalıdır');
    return this.db.transaction(async client => {
      const [product,user]=await Promise.all([client.query('SELECT id FROM products WHERE id=$1 AND is_active=true',[dto.productId]),client.query("SELECT id FROM users WHERE id=$1 AND is_active=true AND role IN ('SUPER_ADMIN','ADMIN','WAREHOUSE','FINANCE')",[dto.recipientUserId])]);
      if(!product.rowCount) throw new NotFoundException('Aktif ürün bulunamadı'); if(!user.rowCount) throw new NotFoundException('Aktif personel bulunamadı');
      const old=await client.query<{id:string}>(`SELECT id FROM commission_rules WHERE product_id=$1 AND recipient_user_id=$2 AND recipient_kind=$3 AND is_active=true FOR UPDATE`,[dto.productId,dto.recipientUserId,dto.recipientKind]);
      if(old.rowCount){await client.query('UPDATE commission_rules SET amount_per_unit=$1,created_by=$2 WHERE id=$3',[dto.amountPerUnit,actor.id,old.rows[0].id]);return {id:old.rows[0].id,updated:true};}
      const created=await client.query<{id:string}>(`INSERT INTO commission_rules(product_id,recipient_user_id,recipient_kind,amount_per_unit,currency,created_by) VALUES($1,$2,$3,$4,'TRY',$5) RETURNING id`,[dto.productId,dto.recipientUserId,dto.recipientKind,dto.amountPerUnit,actor.id]);
      await client.query('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)',[actor.id,'commission.rule.created','commission_rule',created.rows[0].id,JSON.stringify(dto)]); return {...created.rows[0],updated:false};
    });
  }
  async list(){const [rules,entries,staff,products,accounts]=await Promise.all([
    this.db.query(`SELECT r.id,r.product_id,r.recipient_user_id,r.recipient_kind,r.amount_per_unit,r.currency,r.is_active,r.created_at,p.name AS product_name,p.sku,u.email AS recipient_email FROM commission_rules r JOIN products p ON p.id=r.product_id LEFT JOIN users u ON u.id=r.recipient_user_id WHERE r.recipient_kind IN ('STAFF','MANAGER') ORDER BY r.is_active DESC,p.name,u.email`),
    this.db.query(`SELECT e.id,e.order_id,e.order_item_id,e.amount,e.currency,e.status,e.entry_kind,e.created_at,e.finalized_at,e.paid_at,e.reversed_at,e.note,e.source_entry_id,o.order_number,oi.product_name,oi.quantity,u.email AS recipient_email,e.recipient_kind,fu.email AS paid_by_email FROM commission_entries e JOIN orders o ON o.id=e.order_id JOIN order_items oi ON oi.id=e.order_item_id LEFT JOIN users u ON u.id=e.recipient_user_id LEFT JOIN users fu ON fu.id=e.paid_by WHERE e.recipient_user_id IS NOT NULL ORDER BY e.created_at DESC LIMIT 200`),
    this.db.query(`SELECT id,email,role FROM users WHERE is_active=true AND role IN ('SUPER_ADMIN','ADMIN','WAREHOUSE','FINANCE') ORDER BY email`),this.db.query(`SELECT id,name,sku FROM products WHERE is_active=true ORDER BY name LIMIT 500`),this.db.query(`SELECT id,name,currency,account_type FROM finance_accounts WHERE is_active=true ORDER BY name`)]);return {rules:rules.rows,entries:entries.rows,staff:staff.rows,products:products.rows,accounts:accounts.rows};}
  async confirmForOrderItem(input: { dealerId: string; orderId: string; orderItemId: string; productId: string; quantity: number }) {
    const rule = await this.db.query<{ id: string; amount_per_unit: string }>("SELECT id,amount_per_unit FROM commission_rules WHERE (product_id=$1 OR product_id IS NULL) AND starts_at <= now() AND (ends_at IS NULL OR ends_at > now()) ORDER BY product_id NULLS LAST, starts_at DESC LIMIT 1", [input.productId]);
    if (!rule.rows[0]) return null;
    const entry = await this.db.query<{ id: string; amount: string }>("INSERT INTO commission_entries (dealer_id,order_id,order_item_id,rule_id,amount,status,available_at) VALUES ($1,$2,$3,$4,$5,'CONFIRMED',now()) ON CONFLICT (dealer_id,order_item_id,rule_id) DO NOTHING RETURNING id,amount", [input.dealerId, input.orderId, input.orderItemId, rule.rows[0].id, Number(rule.rows[0].amount_per_unit) * input.quantity]); return entry.rows[0] ?? null;
  }
  async awardForDeliveredOrder(orderId:string,actorId:string){return this.db.transaction(async client=>{const items=await client.query<{id:string;product_id:string;quantity:number;currency:string}>('SELECT id,product_id,quantity,currency FROM order_items WHERE order_id=$1 ORDER BY id FOR UPDATE',[orderId]);let created=0;for(const item of items.rows){const rules=await client.query<{id:string;recipient_user_id:string;recipient_kind:string;amount_per_unit:string}>(`SELECT r.id,r.recipient_user_id,r.recipient_kind,r.amount_per_unit FROM commission_rules r JOIN users u ON u.id=r.recipient_user_id WHERE r.product_id=$1 AND r.is_active=true AND r.recipient_kind IN ('STAFF','MANAGER') AND u.is_active=true`,[item.product_id]);for(const rule of rules.rows){const amount=Number((Number(rule.amount_per_unit)*item.quantity).toFixed(2));const entry=await client.query(`INSERT INTO commission_entries(recipient_user_id,recipient_kind,order_id,order_item_id,rule_id,amount,currency,status,entry_kind,note) VALUES($1,$2,$3,$4,$5,$6,$7,'PENDING','EARN','Teslim edilen sipariş primi') ON CONFLICT DO NOTHING RETURNING id`,[rule.recipient_user_id,rule.recipient_kind,orderId,item.id,rule.id,amount,item.currency]);created+=entry.rowCount??0;}}if(created)await client.query('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)',[actorId,'commission.entries.pending','order',orderId,JSON.stringify({count:created})]);return {created};});}
  async finalize(entryId:string,actor:RequestUser){return this.db.transaction(async client=>{const entry=await client.query<{id:string}>(`UPDATE commission_entries SET status='CONFIRMED',finalized_at=now() WHERE id=$1 AND entry_kind='EARN' AND status='PENDING' RETURNING id`,[entryId]);if(!entry.rowCount)throw new ConflictException('Yalnızca bekleyen prim kesinleştirilebilir');await client.query('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4)',[actor.id,'commission.finalized','commission_entry',entryId]);return {id:entryId,status:'CONFIRMED'};});}
  async pay(entryId:string,dto:PayCommissionDto,actor:RequestUser){return this.db.transaction(async client=>{const entry=await client.query<{id:string;amount:string;currency:string;recipient_email:string;order_number:string}>(`SELECT e.id,e.amount,e.currency,u.email AS recipient_email,o.order_number FROM commission_entries e JOIN users u ON u.id=e.recipient_user_id JOIN orders o ON o.id=e.order_id WHERE e.id=$1 AND e.entry_kind='EARN' AND e.status='CONFIRMED' FOR UPDATE`,[entryId]);if(!entry.rowCount)throw new ConflictException('Yalnızca kesinleşmiş ve ödenmemiş prim ödenebilir');const account=await client.query<{id:string}>('SELECT id FROM finance_accounts WHERE id=$1 AND is_active=true AND currency=$2 FOR UPDATE',[dto.accountId,entry.rows[0].currency]);if(!account.rowCount)throw new ConflictException('Prim için aynı para biriminde aktif bir finans hesabı seçin');const transaction=await client.query<{id:string}>(`INSERT INTO finance_transactions(account_id,order_id,kind,amount,payment_status,counterparty_name,reference_number,description,created_by) VALUES($1,(SELECT order_id FROM commission_entries WHERE id=$2),'PRIME_EXPENSE',$3,'PAID',$4,$5,$6,$7) RETURNING id`,[dto.accountId,entryId,entry.rows[0].amount,entry.rows[0].recipient_email,dto.referenceNumber?.trim()||null,`${entry.rows[0].order_number} prim ödemesi`,actor.id]);await client.query(`UPDATE commission_entries SET status='PAID',paid_at=now(),paid_by=$1,finance_transaction_id=$2 WHERE id=$3`,[actor.id,transaction.rows[0].id,entryId]);return {id:entryId,status:'PAID',financeTransactionId:transaction.rows[0].id};});}
  async reverseForOrder(orderId:string,actorId:string,reason:string){return this.db.transaction(async client=>{const entries=await client.query<{id:string;recipient_user_id:string;recipient_kind:string;order_item_id:string;rule_id:string|null;amount:string;currency:string}>(`SELECT id,recipient_user_id,recipient_kind,order_item_id,rule_id,amount,currency FROM commission_entries WHERE order_id=$1 AND entry_kind='EARN' AND status IN ('PENDING','CONFIRMED','PAID') FOR UPDATE`,[orderId]);let reversed=0;for(const e of entries.rows){const result=await client.query(`INSERT INTO commission_entries(recipient_user_id,recipient_kind,order_id,order_item_id,rule_id,amount,currency,status,entry_kind,source_entry_id,note,reversed_at) VALUES($1,$2,$3,$4,$5,$6,$7,'REVERSED','REVERSAL',$8,$9,now()) ON CONFLICT (source_entry_id) WHERE entry_kind='REVERSAL' DO NOTHING RETURNING id`,[e.recipient_user_id,e.recipient_kind,orderId,e.order_item_id,e.rule_id,-Number(e.amount),e.currency,e.id,reason]);if(result.rowCount){await client.query(`UPDATE commission_entries SET status=CASE WHEN status='PAID' THEN status ELSE 'REVERSED' END,reversed_at=now(),note=$1 WHERE id=$2`,[reason,e.id]);reversed++;}}if(reversed)await client.query('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)',[actorId,'commission.reversed','order',orderId,JSON.stringify({count:reversed,reason})]);return {reversed};});}
  async reverse(entryId:string,dto:ReverseCommissionDto,actor:RequestUser){const entry=await this.db.query<{order_id:string}>(`SELECT order_id FROM commission_entries WHERE id=$1 AND entry_kind='EARN'`,[entryId]);if(!entry.rowCount)throw new NotFoundException('Prim kaydı bulunamadı');return this.reverseForOrder(entry.rows[0].order_id,actor.id,dto.note?.trim()||'Yönetici ters kaydı');}
  async deactivateRule(id:string,actor:RequestUser){const r=await this.db.query(`UPDATE commission_rules SET is_active=false,ends_at=now(),ended_by=$1 WHERE id=$2 AND is_active=true RETURNING id`,[actor.id,id]);if(!r.rowCount)throw new NotFoundException('Aktif prim kuralı bulunamadı');return r.rows[0];}
}
