'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AdminNav } from '../components/admin-nav';
import { api } from '../lib/api';
type Config={provider:string;ready:boolean;missing:string[]};
type Shipment={id:string;order_id:string;order_number:string;provider:string;tracking_number:string|null;status:string;label_url:string|null;failure_reason:string|null;recipient_name:string|null;city:string|null;district:string|null;created_at:string};
const status:Record<string,string>={PENDING:'Bekliyor',CREATED:'Gönderi oluşturuldu',IN_TRANSIT:'Taşımada',DELIVERED:'Teslim edildi',FAILED:'Başarısız',CANCELLED:'İptal edildi'};
export default function Shipping(){const [config,setConfig]=useState<Config|null>(null);const [shipments,setShipments]=useState<Shipment[]>([]);const [message,setMessage]=useState('');const load=()=>Promise.all([api<Config>('/admin/orders/shipping/status'),api<Shipment[]>('/admin/orders/shipping')]).then(([c,s])=>{setConfig(c);setShipments(s)}).catch(e=>setMessage(e instanceof Error?e.message:'Kargo kayıtları yüklenemedi'));useEffect(()=>{void load()},[]);return <main><AdminNav/><section><p>SİPARİŞLER / KARGO</p><h1>Kargo işlemleri</h1>{message&&<p role="status">{message}</p>}{config&&<article className="form-card"><h2>Aras Kargo bağlantısı</h2><p>{config.provider==='aras'?(config.ready?'Bağlantı bilgileri hazır. İlk canlı gönderiden önce Aras SetOrder şeması doğrulanmalıdır.':`Bağlantı eksik: ${config.missing.join(', ')}`):'Deneme kargo adaptörü seçili. Canlı gönderi oluşturmaz.'}</p><p>Canlı Aras gönderisi için Render ortam değişkenlerinde müşteri kodu, SetOrder kullanıcı adı/şifresi ve Aras’ın verdiği sözleşme endpoint’i bulunmalıdır.</p></article>}<h2>Son gönderiler</h2><div className="cards">{shipments.length?shipments.map(s=><article key={s.id}><p>{s.provider==='aras'?'Aras Kargo':s.provider} · {status[s.status]??s.status}</p><h2>{s.order_number}</h2><p>{s.tracking_number??'Takip numarası bekleniyor'}</p><p>{s.recipient_name??'—'} · {s.district??''} {s.city??''}</p>{s.label_url&&<a href={s.label_url} target="_blank">Kargo etiketini aç</a>}{s.failure_reason&&<p role="alert">{s.failure_reason}</p>}<p><Link href={`/siparisler/${s.order_id}`}>Sipariş detayı →</Link></p></article>):<article><p>Henüz oluşturulmuş kargo kaydı yok.</p></article>}</div></section></main>}
