import { BadRequestException, Injectable, InternalServerErrorException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { DatabaseService } from '../database/database.service';
import { R2StorageService } from './r2-storage.service';
const allowed=['image/jpeg','image/png','image/webp','image/svg+xml'];
@Injectable()
export class AssetsService {
  constructor(private readonly db:DatabaseService, private readonly storage:R2StorageService){}
  private validate(filename:string,mimeType:string,byteSize:number){if(!allowed.includes(mimeType))throw new BadRequestException('Unsupported image format');if(byteSize>2_000_000)throw new BadRequestException('Image exceeds 2 MB limit');if(!filename.trim())throw new BadRequestException('Filename is required');}
  async createMock(input:{filename:string;mimeType:string;byteSize:number;width?:number;height?:number;placement:string;userId:string}){this.validate(input.filename,input.mimeType,input.byteSize);const key=`mock/${randomUUID()}-${input.filename}`;const asset=await this.db.query<{id:string}>('INSERT INTO assets (original_filename,mime_type,byte_size,width,height,storage_key,status,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[input.filename,input.mimeType,input.byteSize,input.width??null,input.height??null,key,'READY',input.userId]);await this.db.query('INSERT INTO asset_usages (asset_id,placement) VALUES ($1,$2)',[asset.rows[0].id,input.placement]);return{assetId:asset.rows[0].id,storageKey:key,status:'READY'};}
  async upload(input:{filename:string;mimeType:string;buffer:Buffer;placement:string;userId:string}){this.validate(input.filename,input.mimeType,input.buffer.byteLength);const extension=input.filename.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'')||'image';const key=`assets/${randomUUID()}.${extension}`;const asset=await this.db.query<{id:string}>('INSERT INTO assets (original_filename,mime_type,byte_size,storage_key,status,created_by) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id',[input.filename,input.mimeType,input.buffer.byteLength,key,'PENDING',input.userId]);try{const publicUrl=await this.storage.put(key,input.buffer,input.mimeType);await this.db.query("UPDATE assets SET status='READY' WHERE id=$1",[asset.rows[0].id]);await this.db.query('INSERT INTO asset_usages (asset_id,placement) VALUES ($1,$2)',[asset.rows[0].id,input.placement]);return{assetId:asset.rows[0].id,storageKey:key,publicUrl,status:'READY'};}catch(error){await this.db.query("UPDATE assets SET status='FAILED' WHERE id=$1",[asset.rows[0].id]);throw new InternalServerErrorException('Image upload failed; no image was published');}}
}
