'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';

type TrackedOrder = { order_number: string; status: string; total_amount: string; currency: string; created_at: string; shipment_status: string | null; tracking_number: string | null };
const labels: Record<string, string> = { PENDING_PAYMENT: 'Ödeme bekleniyor', PAID: 'Ödendi · hazırlanacak', PROCESSING: 'Hazırlanıyor', SHIPPED: 'Kargoda', DELIVERED: 'Teslim edildi', CANCELLED: 'İptal edildi' };

export default function Orders() {
  const [number, setNumber] = useState(''); const [email, setEmail] = useState(''); const [order, setOrder] = useState<TrackedOrder | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function track(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); setOrder(null); try { const response = await fetch('/api/order-track', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ number, email }) }); const data = await response.json() as TrackedOrder & { message?: string }; if (!response.ok) { setMessage(data.message ?? 'Sipariş bulunamadı.'); return; } setOrder(data); } catch { setMessage('Sipariş servisine ulaşılamıyor.'); } finally { setBusy(false); } }
  return <main className="products"><nav><Link href="/"><strong>TREX <span>TEA</span></strong></Link><Link href="/hesabim">Hesabıma dön</Link></nav><p className="eyebrow">SİPARİŞ TAKİBİ</p><h1>Siparişini takip et</h1><section className="story" style={{ marginTop: '2rem' }}><p>Sipariş numaran ve siparişte kullandığın e-posta ile güvenli olarak durumunu görüntüleyebilirsin.</p><form onSubmit={track}><label>Sipariş numarası<input required value={number} onChange={(event) => setNumber(event.target.value)} placeholder="20261005-000001" /></label><label>E-posta<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><button disabled={busy}>{busy ? 'Sorgulanıyor…' : 'Siparişi sorgula'}</button></form>{message && <p role="status">{message}</p>}{order && <article><p>{new Date(order.created_at).toLocaleString('tr-TR')}</p><h2>{order.order_number}</h2><p><strong>{labels[order.status] ?? order.status}</strong></p><p>{Number(order.total_amount).toLocaleString('tr-TR', { style: 'currency', currency: order.currency })}</p>{order.tracking_number && <p>Kargo takip no: <strong>{order.tracking_number}</strong>{order.shipment_status ? ` · ${order.shipment_status}` : ''}</p>}</article>}<p><Link className="cta" href="/urunler">Çayları keşfet</Link></p></section></main>;
}
