'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AdminNav } from '../../components/admin-nav';
import { api } from '../../lib/api';

type Account = { id: string; name: string; account_type: string };
const categories = ['Kargo', 'Reklam', 'Personel', 'Prim', 'Kira', 'Yazılım', 'Pazar yeri komisyonu', 'Tedarik', 'Vergi', 'Diğer'];

export default function ExpensesPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ accountId: '', amount: '', expenseCategory: 'Kargo', costCenter: '', counterpartyName: '', referenceNumber: '', documentUrl: '', description: '' });
  useEffect(() => { api<Account[]>('/admin/finance/accounts').then((loaded) => { setAccounts(loaded); if (loaded[0]) setForm((current) => ({ ...current, accountId: loaded[0].id })); }).catch((error) => setMessage(error.message)); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { await api('/admin/finance/transactions', { method: 'POST', body: JSON.stringify({ ...form, kind: 'EXPENSE', amount: Number(form.amount), paymentStatus: 'PAID', counterpartyName: form.counterpartyName || undefined, referenceNumber: form.referenceNumber || undefined, documentUrl: form.documentUrl || undefined, costCenter: form.costCenter || undefined }) }); setMessage('Masraf kaydedildi.'); setForm((current) => ({ ...current, amount: '', counterpartyName: '', referenceNumber: '', documentUrl: '', description: '' })); } catch (error) { setMessage(error instanceof Error ? error.message : 'Kaydedilemedi'); } }
  return <main><AdminNav/><section><p>FİNANS / MASRAFLAR</p><h1>Masraf girişi</h1><p>Masrafı hangi hesaptan çıktığını, kategorisini ve belge bilgisini girerek kaydedin.</p>{message && <p role="status">{message}</p>}<form className="form-card" onSubmit={submit}><div className="form-grid"><label>Çıkış hesabı<select required value={form.accountId} onChange={(event) => setForm((current) => ({ ...current, accountId: event.target.value }))}><option value="">Seçin</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Masraf kategorisi<select value={form.expenseCategory} onChange={(event) => setForm((current) => ({ ...current, expenseCategory: event.target.value }))}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Tutar (TL)<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))}/></label><label>Masraf merkezi<input value={form.costCenter} placeholder="Depo, satış, yönetim..." onChange={(event) => setForm((current) => ({ ...current, costCenter: event.target.value }))}/></label><label>Firma / kişi<input value={form.counterpartyName} onChange={(event) => setForm((current) => ({ ...current, counterpartyName: event.target.value }))}/></label><label>Dekont / fatura no<input value={form.referenceNumber} onChange={(event) => setForm((current) => ({ ...current, referenceNumber: event.target.value }))}/></label><label className="wide">Belge bağlantısı<input value={form.documentUrl} placeholder="Medya alanından yüklediğiniz belgenin bağlantısı" onChange={(event) => setForm((current) => ({ ...current, documentUrl: event.target.value }))}/></label><label className="wide">Açıklama<textarea required value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))}/></label></div><button>Masrafı kaydet</button></form></section></main>;
}
